# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0008_auto_20180627_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='vegetarian_meal',
            field=models.BooleanField(default=False),
        ),
    ]
