# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-07 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0010_auto_20180707_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sent_save_the_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='is_child',
            field=models.BooleanField(default=False),
        ),
    ]
