# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-15 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0012_auto_20190121_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='present_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
