# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-07-21 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0013_userprofile_present_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sent_photos_link',
            field=models.BooleanField(default=False),
        ),
    ]
